### ISSUE TITLE
permission のカラムの整合が取れていない

### ISSUE THREAD

**Issue by hsakamoto123** [FIWARE/tutorials.Roles-Permissions#16]
controllers/api/permissions.js および models/permissions.js の permission のカラムと、mysql の permission テーブルのカラムとが、整合が取れていない。

js の方には、以下の３つが記述されているが、テーブルにはこれらのカラムがない。
　regex_entity_ids
　regex_attributes
　regex_types
mysql 側に、これらのカラムの登録が必要と考えているが、alter table しようにも型がわからないし、初期値の設定の要否がわからないので困っている。
対応できる情報を提供して欲しい。

**Comment by hsakamoto123** [comment]
パーミッションの詳細取得のリクエスト実行時で、以下のエラー。
{"error":{"message":"Internal error","code":500,"title":"Internal error"}}
コンテナのログは、以下。
{"log":"2022-12-06T14:14:25.402Z idm:api-permissions Error: SequelizeDatabaseError: Unknown column 'regex_entity_ids' in 'field list'\n","stream":"stderr","time":"2022-12-06T14:14:25.40282719Z"}

型は適当に決めて無理やり、以下の alter table すると、上記のリクエストは動作したが、
　alter table permission add regex_entity_ids varchar(？？);
　alter table permission add regex_attributes varchar(？？);
　alter table permission add regex_types varchar(？？);
パーミッションの更新実行で、次のエラー。
{"error":{"message":"if use_authorization_service_header is set, authorization_service_header needs to be set","code":400,"title":"Bad Request"}}
コンテナのログは、以下。
{"log":"2022-12-06T15:24:59.515Z idm:api-permissions Error: [object Object]\n","stream":"stderr","time":"2022-12-06T15:24:59.515660589Z"}

js 側の型？と、mysql 側のテーブルの型？値？ との不整合だと想像するが、対処方法がわからない。

エラーになるリクエストが、正しく動かせる情報を教えて欲しい。

**Comment by hsakamoto123** [comment]
下記の変更を反映して、動作できました。

https://github.com/FIWARE/tutorials.Roles-Permissions/pull/17/files

**Comment by fisuda** [comment]
The PR #17 has been merged. It would be great if  you could close this issue.
