### ISSUE TITLE
Creating an application: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by CristinaVTx** [FIWARE/tutorials.Roles-Permissions#6]
I'm following the security tutorials for access control through the API and postman collections.
I finished all the tutorials properly, but I haven't been able to create an application through the API.

I have used the POST request that appears in the collection, but it returns an 500 error (Internal Error). The most detailed error that appears in the logs is:

> TypeError: Cannot read property 'includes' of undefined

The body that I use is:

`{
  "application": {
    "name": "Application test",
    "description": "Testing",
    "redirect_uri": "http://testing/login",
    "url": "http://testing",
    "grant_type": [
      "authorization_code",
      "implicit",
      "password"
    ]
  }
}`

Is it possible there's something wrongly defined?
At the moment I have users, roles and organizations created. The administrator user is Alice (the one in the example) with the updated token and the OAuth token that you provide.

Thank you in advance.

**Comment by jason-fox** [comment]
There was a change needed in the body of the request as a breaking change for 7.5.1., the payload should look like:

```
curl -X POST \
  http://localhost:3005/v1/applications \
  -H 'Content-Type: application/json' \
  -H 'X-Auth-token: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' \
  -d '{
  "application": {
    "name": "Tutorial Application",
    "description": "FIWARE Application protected by OAuth2 and Keyrock",
    "redirect_uri": "http://context-provider/login",
    "url": "http://context-provider",
    "grant_type": [
      "authorization_code",
      "implicit",
      "password"
    ],
    "token_types": ["permanent"]
  }
}'
```

There is still a bug in the IDM code as it can't deal with the `token_types` attribute being missing.
